#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch openl.foam

mkdir -p constant/triSurface

cp -f QHullOrigin.stl constant/triSurface/

runApplication blockMesh

# z-dir refinement for free surface
runApplication topoSet -dict system/topoSetDict
runApplication refineMesh -dict system/refineMeshDict -overwrite

runApplication surfaceFeatureExtract

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runParallel redistributePar -reconstruct -constant -overwrite

runApplication renumberMesh -constant -overwrite

#------------------------------------------------------------------------------